services:
  postgres:
    image: postgres:16
    container_name: eventlink-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: downtimeprod_db
      POSTGRES_USER: adminevent
      POSTGRES_PASSWORD: 

    ports:
      - "5432:5432"

    volumes:
      - eventlink_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U downtimeprod -d downtimeprod_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  eventlink_postgres_data:
