export enum OrganizationType {
  COMPANY = 'COMPANY',
  PORT = 'PORT',
  HOSPITAL = 'HOSPITAL',
  AIRPORT = 'AIRPORT',
  INDUSTRY = 'INDUSTRY',
  LOGISTICS = 'LOGISTICS',
  ENERGY = 'ENERGY',
  WILAYA = 'WILAYA',
  GOVERNMENT = 'GOVERNMENT',
  UNIVERSITY = 'UNIVERSITY',
  COMMUNE = 'COMMUNE',
  OTHER = 'OTHER',
}